import Foundation

final class DataStore: ObservableObject {
    @Published var poses: [Pose] = []
    @Published var symptoms: [Symptom] = []
    @Published var meditations: [Meditation] = []

    static let shared = DataStore()

    private init() {
        poses = Self.curatedPoses
        symptoms = Self.curatedSymptoms
        meditations = Self.curatedMeditations
    }

    func pose(for id: String) -> Pose? {
        poses.first { $0.id == id }
    }
}

private extension DataStore {
    static let curatedPoses: [Pose] = [
        Pose(id: "easy_pose", nameJa: "安楽座", nameEn: "Easy Pose", sanskrit: "Sukhasana", category: "座位", categoryEn: "Seated", difficulty: 1, duration: 3, benefits: ["呼吸が深まり、心が落ち着く", "骨盤と背骨の感覚を整える", "瞑想の準備に向いている"], benefitsEn: ["Deepens breathing and calms the mind", "Aligns pelvis and spine awareness", "Prepares you for meditation"], instructions: ["坐骨を床に根づかせ、背骨を長く保つ", "肩を下げ、胸の奥に空間を作る", "鼻から吸って、長く吐く呼吸を続ける"], instructionsEn: ["Root your sit bones into the floor, lengthen the spine", "Lower the shoulders, create space in the chest", "Breathe in through the nose and exhale slowly"], cautions: ["膝や股関節がつらい場合はブランケットを敷く"], cautionsEn: ["Place a blanket under hips if knees or hips feel tight"], chakra: "muladhara", imageFile: "YogaHero"),
        Pose(id: "tree_pose", nameJa: "木のポーズ", nameEn: "Tree Pose", sanskrit: "Vrksasana", category: "バランス", categoryEn: "Balance", difficulty: 2, duration: 2, benefits: ["集中力と体幹を育てる", "足裏の安定感を高める", "姿勢を美しく整える"], benefitsEn: ["Builds focus and core strength", "Strengthens foot stability", "Improves posture"], instructions: ["片足に重心を乗せ、足裏で床を押す", "反対の足を内ももかふくらはぎに添える", "胸の前で手を合わせ、視線を一点に置く"], instructionsEn: ["Shift weight to one foot, press the sole into the floor", "Place the other foot on inner thigh or calf", "Bring hands together at chest, gaze at one point"], cautions: ["膝の横に足裏を強く押しつけない"], cautionsEn: ["Do not press the foot directly against the knee"], chakra: "muladhara", imageFile: "PoseTree"),
        Pose(id: "cat_cow", nameJa: "キャット＆カウ", nameEn: "Cat Cow", sanskrit: "Marjaryasana Bitilasana", category: "背骨", categoryEn: "Spine", difficulty: 1, duration: 4, benefits: ["背中と肩のこわばりをゆるめる", "呼吸と動きを合わせやすい", "朝のウォームアップに最適"], benefitsEn: ["Releases stiffness in back and shoulders", "Syncs breath with movement", "Perfect morning warm-up"], instructions: ["四つ這いになり、手首を肩の下へ置く", "吸う息で胸を前へ、吐く息で背中を丸める", "ゆっくり波のように背骨を動かす"], instructionsEn: ["Start on all fours, wrists under shoulders", "Inhale to arch the chest, exhale to round the back", "Move the spine in a slow wave-like motion"], cautions: ["手首が痛い場合は拳か前腕で支える"], cautionsEn: ["Use fists or forearms if wrists hurt"], chakra: "svadhisthana", imageFile: "RestorativeProps"),
        Pose(id: "downward_dog", nameJa: "下向きの犬のポーズ", nameEn: "Downward Dog", sanskrit: "Adho Mukha Svanasana", category: "全身", categoryEn: "Full Body", difficulty: 2, duration: 3, benefits: ["肩、背中、脚裏を伸ばす", "血流を促し、頭をすっきりさせる", "全身の巡りを整える"], benefitsEn: ["Stretches shoulders, back, and hamstrings", "Promotes blood flow and clears the head", "Improves full-body circulation"], instructions: ["手のひらを広げ、坐骨を斜め上へ引く", "膝は曲がっていてよいので背中を長くする", "首の力を抜き、呼吸を広げる"], instructionsEn: ["Spread your palms, lift sit bones up and back", "Bend knees as needed, keep the back long", "Release the neck and breathe deeply"], cautions: ["高血圧や手首の痛みがある場合は無理をしない"], cautionsEn: ["Avoid if you have high blood pressure or wrist pain"], chakra: "vishuddha", imageFile: "YogaHero"),
        Pose(id: "warrior_i", nameJa: "戦士のポーズ I", nameEn: "Warrior I", sanskrit: "Virabhadrasana I", category: "立位", categoryEn: "Standing", difficulty: 3, duration: 2, benefits: ["脚力と意志を育てる", "胸と股関節を開く", "前向きなエネルギーを作る"], benefitsEn: ["Builds leg strength and willpower", "Opens chest and hip flexors", "Creates forward energy"], instructions: ["前足を踏み込み、後ろ足で床を押す", "骨盤を正面へ向け、両腕を上げる", "下半身は強く、呼吸はやわらかく保つ"], instructionsEn: ["Step the front foot forward, press the back foot down", "Square the hips forward, raise both arms", "Strong lower body, soft breath"], cautions: ["腰を反らせすぎず、肋骨を軽くしまう"], cautionsEn: ["Don't over-arch the lower back, gently draw in the ribs"], chakra: "manipura", imageFile: "PoseTree"),
        Pose(id: "childs_pose", nameJa: "チャイルドポーズ", nameEn: "Child's Pose", sanskrit: "Balasana", category: "休息", categoryEn: "Rest", difficulty: 1, duration: 5, benefits: ["背中と腰を休める", "安心感を取り戻す", "疲れた日にも行いやすい"], benefitsEn: ["Rests the back and lower body", "Restores a sense of safety", "Easy to do even on tired days"], instructions: ["正座から上体を前へ倒す", "額を床かクッションに預ける", "背中に呼吸を送るようにゆっくり吐く"], instructionsEn: ["From kneeling, fold the torso forward", "Rest forehead on the floor or a cushion", "Breathe slowly into the back body"], cautions: ["膝が痛い場合は太ももとふくらはぎの間にタオルを入れる"], cautionsEn: ["Place a towel between thighs and calves if knees hurt"], chakra: "ajna", imageFile: "RestorativeProps"),
        Pose(id: "bridge_pose", nameJa: "橋のポーズ", nameEn: "Bridge Pose", sanskrit: "Setu Bandha Sarvangasana", category: "胸を開く", categoryEn: "Chest Opening", difficulty: 2, duration: 3, benefits: ["胸を開き、呼吸を広げる", "お尻と背中をやさしく強化する", "気分を前向きにする"], benefitsEn: ["Opens the chest and deepens breathing", "Gently strengthens glutes and back", "Lifts your mood"], instructions: ["仰向けで膝を立て、足を腰幅に置く", "息を吐きながら骨盤を持ち上げる", "胸をあごへ近づけ、首は動かさない"], instructionsEn: ["Lie on your back, knees bent, feet hip-width apart", "Exhale as you lift the pelvis", "Draw the chest toward the chin, keep the neck still"], cautions: ["首に違和感がある場合は高さを下げる"], cautionsEn: ["Lower the height if you feel discomfort in the neck"], chakra: "anahata", imageFile: "YogaHero"),
        Pose(id: "corpse_pose", nameJa: "シャヴァーサナ", nameEn: "Corpse Pose", sanskrit: "Savasana", category: "瞑想", categoryEn: "Meditation", difficulty: 1, duration: 8, benefits: ["緊張をほどき、回復を促す", "練習の効果を体に馴染ませる", "睡眠前にもおすすめ"], benefitsEn: ["Releases tension and promotes recovery", "Lets the body absorb the practice", "Great before sleep"], instructions: ["仰向けになり、手足を自然に開く", "全身の重さを床に預ける", "呼吸を操作せず、静けさを味わう"], instructionsEn: ["Lie on your back, arms and legs relaxed", "Surrender your full weight to the floor", "Let the breath flow naturally, enjoy the stillness"], cautions: ["腰が浮く場合は膝下にクッションを置く"], cautionsEn: ["Place a cushion under the knees if the lower back lifts"], chakra: "sahasrara", imageFile: "MeditationCorner")
    ]

    static let curatedSymptoms: [Symptom] = [
        Symptom(id: "stress", nameJa: "ストレス", nameEn: "Stress", icon: "leaf.fill", description: "呼吸を長くし、背中と胸をゆるめて神経を落ち着かせます。", descriptionEn: "Calm the nervous system with breath and gentle opening.", recommendedPoses: [SymptomPose(poseId: "childs_pose", reason: "安心感を作る休息姿勢", reasonEn: "Grounding rest", duration: 5), SymptomPose(poseId: "easy_pose", reason: "呼吸を整える", reasonEn: "Breath focus", duration: 3)], avoidPoses: ["強い逆転"], tips: ["吐く息を吸う息より少し長くする", "部屋の明かりを落として行う"], tipsEn: ["Lengthen the exhale", "Lower the lights"]),
        Symptom(id: "stiff_shoulders", nameJa: "肩こり", nameEn: "Stiff Shoulders", icon: "figure.walk", description: "肩甲骨と胸まわりを動かし、デスクワークの緊張をほどきます。", descriptionEn: "Release desk tension around the shoulders.", recommendedPoses: [SymptomPose(poseId: "cat_cow", reason: "背骨と肩甲骨を動かす", reasonEn: "Mobilizes spine", duration: 4), SymptomPose(poseId: "bridge_pose", reason: "胸を開く", reasonEn: "Opens chest", duration: 3)], avoidPoses: ["痛みを伴う腕上げ"], tips: ["肩をすくめず首を長く保つ", "痛気持ちいい範囲に留める"], tipsEn: ["Keep the neck long", "Stay gentle"]),
        Symptom(id: "sleep", nameJa: "眠りの質", nameEn: "Sleep", icon: "moon.stars.fill", description: "副交感神経に切り替える、夜向けの静かな組み合わせです。", descriptionEn: "A quiet evening sequence for better rest.", recommendedPoses: [SymptomPose(poseId: "corpse_pose", reason: "全身を休める", reasonEn: "Deep rest", duration: 8), SymptomPose(poseId: "childs_pose", reason: "安心感を高める", reasonEn: "Safety cue", duration: 5)], avoidPoses: ["寝る直前の強い後屈"], tips: ["スマホを伏せてから始める", "最後は照明を暗くする"], tipsEn: ["Put the phone down", "Dim the room"])
    ]

    static let curatedMeditations: [Meditation] = [
        Meditation(id: "breath", nameJa: "呼吸を整える瞑想", nameEn: "Breath Reset", icon: "wind", durationOptions: [3, 5, 10], defaultDuration: 5, description: "吸う、吐く。その単純なリズムに戻るための短い瞑想です。", descriptionEn: "Return to a simple breathing rhythm.", benefits: ["頭が静かになる", "緊張がゆるむ", "練習前の集中が高まる"], benefitsEn: ["Clearer mind", "Less tension", "Better pre-practice focus"], instructions: ["背骨を長く座る", "4拍で吸い、6拍で吐く", "考えが浮かんだら呼吸へ戻る"], instructionsEn: ["Sit tall", "Inhale for 4, exhale for 6", "When thoughts arise, return to the breath"], chakra: nil, backgroundMusic: "silent", difficulty: 1, tags: ["朝", "夜", "初心者"], tagsEn: ["Morning", "Night", "Beginner"], chakraSequence: nil, mantra: nil, mantraPhonetic: nil),
        Meditation(id: "chakra", nameJa: "チャクラを巡る瞑想", nameEn: "Chakra Flow", icon: "sparkles", durationOptions: [7, 14], defaultDuration: 7, description: "7つのチャクラを下から順に感じ、心身のバランスを整えます。", descriptionEn: "Move awareness through seven chakras.", benefits: ["自己観察が深まる", "心身のバランスを感じやすい"], benefitsEn: ["Deeper self-awareness", "Balanced mind-body connection"], instructions: ["骨盤底から頭頂へ意識を移す", "各場所に色の光をイメージする", "最後は全身を一つの呼吸で包む"], instructionsEn: ["Shift attention from root to crown", "Visualize colored light at each point", "Finish by wrapping the whole body in one breath"], chakra: "sahasrara", backgroundMusic: "silent", difficulty: 2, tags: ["チャクラ", "集中"], tagsEn: ["Chakra", "Focus"], chakraSequence: nil, mantra: "Om Shanti", mantraPhonetic: "オーム シャンティ")
    ]
}
